name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Install dependencies
      run: |
        sudo apt install gcc xserver-xorg alsa-lib libxcursor libxi libxinerama libxrandr mesa-libs mesa-utils libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
        go mod tidy

    - name: Test
      run: |
        export DISPLAY=":99.0"
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        make test
